### ISSUE TITLE
Send invitation email via queue

### ISSUE THREAD

**Issue by ServerJunge** [agilepixels/laravel-invitable#1]
Hi,

I really like your package! Thank you for that! 

Is there any example on how to send the invitation email via a queue? 

Thank you.

**Comment by lexdewilligen** [comment]
You could configure a custom InvitationNotificationModel as NotificationModel. Just copy the current NotificationModel and make it implement ShouldQueue. Then configure it like this:
```
    /*
    |--------------------------------------------------------------------------
    | Notification Model
    |--------------------------------------------------------------------------
    */
    'NotificationModel' => 'App\Notifications\InvitationNotification',
```
That should do the job for you!
